# Generated by Django 3.2.9 on 2021-11-12 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='docstore.folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='topic',
            field=models.ManyToManyField(blank=True, null=True, related_name='folders', to='docstore.Topic'),
        ),
    ]
